name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore EpicKit.csproj

      - name: Build EpicKit
        run: dotnet build EpicKit.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack EpicKit.csproj --configuration Release --no-build -o ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json